### ISSUE TITLE
Bug when removing a query after searching

### ISSUE THREAD

**Issue by Evan-Leon** [mediacloud/web-search#326]
Trying to remove a query after sending a search causes the app to break.

**Comment by evansuslovich** [comment]
I found that if I commented lines 140-144 in TabbedSearch (CountOverTimeResults, TotalAttentionResults, SampleStories, TopWords, and TopLanguages) 

To simplify this problem, I only want to look at CountOverTimeResults (comment all others) 

To identify the issue, we have to find where the error arrises and it reaches queryTitle.js with a "Cannot read properties of undefined" 

To find where queryTitle.js is called, we have to look first at CountOverTimeResults which calls prepareCountOverTimeData which calls queryTitle. 

Issue: 
"A" in query 1 
"B" in query 2 
Search Button 
Remove Query (removing query 2 or "B") 

With logging, I found that if I printed out the queryState and the index inside queryTitle, failure would arise when trying to access index 1 of queryState which would result in the "B" query; however, since it's already been deleted and queryTitle isn't getting updated indexing, it breaks the app.  


Call 1: queryState has a length of 2, index 0 (Yay!) --> "A" Query
Call 2: queryState has a length of 2, index 1 (Yay!) --> "B" Query 


![Screen Shot 2023-04-28 at 3 42 55 PM](https://user-images.githubusercontent.com/63474660/235238699-976cfcfb-1b71-4930-a10d-50b18732f2db.png)


Call 1: queryState has a length of 1, index 0 (Yay!) --> "A" Query
Call 2: queryState has a length of 1, index 1 (NO!) -->  undefined because that query has already been deleted. 


![Screen Shot 2023-04-28 at 3 40 58 PM (2)](https://user-images.githubusercontent.com/63474660/235238404-56c16430-b824-4056-815b-7f98546b7a41.png)

**Comment by evansuslovich** [comment]
useGetCountOverTimeMutation() fetches data which gets passed from CountOverTimeResults to prepareCountOverTimeData to queryTitle. I think this data should be dispatched to the state because despite the query being deleted with removeQuery, the data isn't and the files aren't understanding that change.
